config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get 'jobs', to: 'jobs#index'
  resources :jobs do
    resources :favourites, only: [:create]
    resources :job_applications, only: [:create]
  end
  resources :favourites, only: [:index, :destroy]
  resources :job_applications, except: [:create]

  resources :job_applications, only: :show do
  resources :messages, only: :create
  end
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :favourites
  has_many :job_applications

  has_one_attached :photo
  # We are using Cloudinary
  # mount_uploader :image, ImageUploader
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :job_application
  # after_create_commit :broadcast_message

  # private

  # def broadcast_message
  #   broadcast_append_to "job_application_#{job_application.id}_messages",
  #                       partial: "messages/message",
  #                       locals: { message: self, user: user },
  #                       target: "messages"
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites
  has_many :jobs
  has_many :job_applications

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :company_name, :experience, :skills, :location, :education, :company_description, :employer])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = current_user.favourites
    render 'index'
  end
  def create
    @favourite = Favourite.new
    job = Job.find(params["job_id"])
    @favourite.job = job
    @favourite.user = current_user
    if @favourite.save
      redirect_to job_path(job)
    else
      render 'jobs/show'
    end
  end

  def destroy
    @favourite = Favourite.find(params["id"])
    @favourite.destroy
    redirect_to jobs_path, notice: 'Job was removed from your Favourites.'
  end

  private
  def favourite_params
    params.require(:favourite).permit(:job_id)
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.employer == true
      # @pending_applications = current_user.jobs.map { |job| job.job_applications.select { |application| application.status == "pending" && application.user = !current_user}}
      # @confirmed_applications = current_user.jobs.map { |job| job.job_applications.select {|application |application.status == "confirmed" && application.user == !current_user}}
      # raise
      apps = current_user.jobs.map {|job| job.job_applications.reject { |application| application.user == current_user}}.flatten
      @pending_applications = apps.select{|app| app.status == 'pending'}
      @confirmed_applications = apps.select{|app| app.status == 'confirmed'}
     # @pending_applications = current_user.job_applications.where(status: "pending")
     # @confirmed_applications = current_user.job_applications.where(status: "confirmed")

    else
      @pending_applications = current_user.job_applications.where(status: "pending")
      @confirmed_applications = current_user.job_applications.where(status: "confirmed")
    end
  end

  def new
    @job = Job.find(params[:id])
    @application = JobApplication.new
  end

  def create
    @application = JobApplication.new(status: "pending")
    @application.user = current_user
    @job = Job.find(params[:job_id])
    @application.job = @job
    if @application.save
      redirect_to job_applications_path
    else
      render 'jobs/show', job: @job
    end
  end

  def show
    @job_application = JobApplication.find(params[:id])
    @job = @job_application.job
    @message = Message.new
  end

  def edit
    @job_application = JobApplication.find(params[:id])

  end

  def update
    @job = JobApplication.find(params[:id])
    @job.update(job_params)
    redirect_to job_applications_path
  end
end

private

def job_params
  params.require(:job_application).permit(:status, :interview_outcome, :interview_date, :interview_completion)
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if current_user.employer
      @jobs = Job.where(user: current_user)
    else
      @jobs = Job.all
    end
    if params[:query].present?
      @jobs = @jobs.where("job_title ILIKE ?", "%#{params[:query]}%")
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to job_path(@job)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @job = Job.find(params[:id])
    @favourite = Favourite.new
    @already_favourited = Favourite.where(job: @job, user: current_user).last
  end

  private

  def job_params
    params.require(:job).permit(:job_title, :company_name, :company_description, :company_size, :location, :salary, :photo)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @job_application = JobApplication.find(params[:job_application_id])
    @message = Message.new(message_params)
    @message.job_application = @job_application
    @message.user = current_user
    if @message.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:messages, partial: "messages/message",
            locals: { message: @message, user: current_user })
        end
        format.html { redirect_to job_application_path(@job_application) }
      end
    else
      render "job_application/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favourites/index.html.erb
<div class="container favourites-padding">

  <h1 class="mb-3">Saved jobs</h1>

  <% if @favourites.nil? || @favourites.empty? %>

    <p>You haven't saved any jobs yet. Start exploring and save jobs you're interested in!</p>

  <% else %>

    <div class="card-grid">
      <% @favourites.each do |favourite| %>
        <div style="position:relative;">

          <%= link_to job_path(favourite.job), class:"card-favourite border-blue"  do %>

            <%= cl_image_tag favourite.job.photo.key, class: "card-favourite-img" if favourite.job.photo.attached? %>
            <div class="card-favourite-info">
              <h3><%= favourite.job.job_title %></h3>
              <h4><%= favourite.job.company_name %></h4>
              <p><%= favourite.job.location %></p>
              <p> £<%= favourite.job.salary %></p>
            </div>

          <% end %>

          <div class="favourite-position-absolute">
            <%= link_to favourite_path(favourite), class:"fav-btn", data: {turbo_method: :delete } do %>
              <i class="fa-solid fa-heart"></i>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>

  <% end %>
</div>

app/views/job_applications/edit.html.erb
<div class="container d-flex" style="margin-bottom: 100px;">
  <div class="job-application-edit-card">
    <h1 style="text-align:center;">Applicant details</h1>
    <h4>Name:</h4>
    <p class="card-text"><%= @job_application.user.first_name %> <%= @job_application.user.last_name %></p>
    <h4>Skills:</h4>
    <p class="card-text"><%= @job_application.user.skills %></p>
    <h4>Education:</h4>
    <p class="card-text"><%= @job_application.user.education %></p>


    <%= simple_form_for(@job_application) do |f| %>
      <% if @job_application.status == 'pending' %>
        <%= f.input :status, as: :select, collection: ["pending", "rejected", "confirmed"] %>
      <% end %>
      <% if @job_application.status == 'confirmed' %>
        <%= f.input :interview_date, html5: true%>
        <%= f.label :inteview_completion %>
        <%= f.input :interview_completion, label: "check if applicant completed interview" %>
      <% end %>
      <% if @job_application.interview_date.present? && @job_application.interview_date < Date.today %>
      <div>
        <%= f.label :interview_outcome, style: "display:block;" %>
        <%= f.text_area :interview_outcome, placeholder: "place offer or rejection letter here...", style: "width:100%; border-color: #1B4965"%>
      </div>
      <% end %>
        <%= f.submit "update application", class: "btn-more-details", style: "font-size: 16px;width:100%;"%>
    <% end %>
  </div>

  <div class="job-application-edit-card">
    <h3><%= @job_application.job.job_title %></h3>
     <h4>Company  name:</h4>
      <p class="card-text"><%= @job_application.job.company_name %></p>
      <h4>Company description: </h4>
      <p class="card-text"><%= @job_application.job.company_description %></p>
      <h4>Company size</h4>
      <p class="card-text"><%= @job_application.job.company_size %></p>
      <h4>Location: </h4>
      <p class="card-text"><%= @job_application.job.location %></p>
      <h4>Job Description: </h4>
      <p class="card-text"><%= @job_application.job.job_description %></p>
      <h4>Salary: </h4>
      <p class="card-text"><%= @job_application.job.salary %></p>
  </div>
</div>

app/views/job_applications/index.html.erb
<% if current_user.employer %>
<div class="card">
<div class= "container d-flex card-job-application" style ="margin-bottom:100px">
    <div class="user-info">
      <h2>About You</h2>
      <div class="profile-card-user-info">
         <h6><i class="fa-solid fa-user"></i>        <%= current_user.username %></h6>
         <h6><i class="fa-solid fa-phone"></i>      <%= current_user.phone_number %></h6>
         <h6><i class="fa-solid fa-envelope"></i>    <%= current_user.email %></h6>
       </div>
       <div class="profile-card-user-info">
         <h6><i class="fa-solid fa-briefcase"></i>     <%= current_user.job_experience %></h6>
          <h6><i class="fa-solid fa-business-time"></i>  <%= current_user.experience %></h6>
          <h6><i class="fa-solid fa-location-dot"></i>   <%= current_user.location %></h6>
       </div>
       <div class="profile-card-user-info">
         <p><span>Skills:  </span> <%= current_user.skills %> </p>
         </div>
      </div>
    <div class="card-job-application-right">
      <div class="title">
          <h3>Job Applicants</h3>
      </div>
        <div class="job-applied">
            <h5>Pending: </h5>
           <% unless @pending_applications.empty? %>
                  <% @pending_applications.each do |application| %>
                      <div class="card-product" id="border-width">
                       <%= cl_image_tag application.job.photo.key if application.job.photo.attached? %>
                             <div class="card-product-infos application-card">
                              <div class="application-card-title">
                                 <h2> <%= application.job.job_title %> </h2>
                                 <p><%= application.job.company_name %></p>
                              </div>
                               <div class="status">
                                    <p> <span style="font-weight: 600">Status:</span> <%= application.status %> </p>
                                    <p class="view-application-button"><%= link_to "View Application", edit_job_application_path(application)%></p>
                               </div> </div>
                      </div>
                  <%end%>
          <% else %>
                  <div style="border: 1px solid #5FA8D3; margin:20px; font-weight: 500; justify-content: space-evenly; font-size: 20px"class="card-product">
                    <div class="card-product-infos">
                    <p>No current pending applications</p>
                    </div>
                  </div>
          <% end %>
        </div>
      <div class="confirmed">
          <h5>Confirmed: </h5>
          <div class="cards-job-application">
              <% unless @confirmed_applications.empty? %>
                <% @confirmed_applications.each do |application| %>
                    <div class="card-product" id="border-width">
                     <%= cl_image_tag application.job.photo.key if application.job.photo.attached? %>
                              <div class="card-product-infos application-card">
                                  <div class="application-card-title">
                                    <h2><%= application.job.job_title %></h2>
                                    <p><%= application.job.company_name%><p>
                                  </div>
                                  <div class="status">
                                    <p> <span style="font-weight: 600">Status:</span> <%= application.status %> </p>
                                    <p class="view-application-button"><%= link_to "View Application", job_application_path(application) %></p>
                                  </div>
                             </div>
                      </div>

                <% end %>
            </div>
            <% else %>
             <div style="border: 1px solid #5FA8D3; margin:20px; font-weight: 500; justify-content: space-evenly; font-size: 20px;"class="card-product">
                <div class="card-product-infos">
                <p>No current confirmed applications</p>
              </div>
            </div>
          <% end %>
        </div>
     </div>
      </div>
  <% else %>
<div class= "container d-flex card-job-application">
    <div class="user-info">
        <h2>About You</h2>
        <div class="profile-card-user-info">
            <h6><i class="fa-solid fa-user"></i>        <%= current_user.username %></h6>
            <h6><i class="fa-solid fa-phone"></i>      <%= current_user.phone_number %></h6>
            <h6><i class="fa-solid fa-envelope"></i>    <%= current_user.email %></h6>
            </div>
         <div class="profile-card-user-info">
            <h6><i class="fa-solid fa-briefcase"></i>     <%= current_user.job_experience %></h6>
             <h6><i class="fa-solid fa-business-time"></i> <%= current_user.experience %></h6>
              <h6><i class="fa-solid fa-location-dot"></i>   <%= current_user.location %></h6>
            </div>
         <div class="profile-card-user-info">
         <h6>Skills: </h6>
         <p><%= current_user.skills %> </p>
         </div>
     </div>
    <div class="card-job-application-right">
        <div class="title">
          <h3>Your Applications</h3>
        </div>
        <div class="pending">
            <h5>Pending: </h5>
            <% unless @pending_applications.empty? %>
              <% @pending_applications.each do |application| %>
                 <div class="card-product" id="border-width">
                     <%= cl_image_tag application.job.photo.key if application.job.photo.attached? %>
                     <div class="card-product-infos application-card">
                        <div class="application-card-title">
                           <h2><%= application.job.job_title %></h2>
                           <p><%= application.job.company_name%><p>
                        </div>
                        <div class="status">
                           <p> <span style="font-weight: 600">Status:</span> <%= application.status %> </p>
                        </div>
                     </div>
                </div>
              <% end %>
              <% else %>
              <div style="border: 1px solid #5FA8D3; margin:20px; font-weight: 500; justify-content: space-evenly; font-size: 20px;"class="card-product">
                  <div class="card-product-infos">
                    <p>No current pending applications</p>
                  </div>
              </div>
            <% end %>
        </div>
        <div class="confirmed">
            <h5>Confirmed:</h5>
            <% unless @confirmed_applications.empty? %>
              <% @confirmed_applications.each do |application| %>
                <div class="card-product" id="border-width" style="height:auto">
                   <%= cl_image_tag application.job.photo.key if application.job.photo.attached? %>
                     <div class="card-product-infos application-card">
                         <div class="application-card-title">
                                    <h2><%= application.job.job_title %></h2>
                                    <p><%= application.job.company_name%><p>
                                    <div>
                                       <h6>Interview Info:</h6>
                                        <p> Time: <%= application.interview_date%></p>
                                        <p>Interviewer: <%= application.job.user.first_name%><p>
                                    </div>
                          </div>
                           <div class="status">
                                    <p> <span style="font-weight: 600">Status:</span> <%= application.status %> </p>
                                    <p class="view-application-button"><%= link_to "View Application", job_application_path(application) %></p>
                           </div>
                     </div>
                </div>
              <% end %>
            <% else %>
            <div style="border: 1px solid #5FA8D3; margin:20px; font-weight: 500; justify-content: space-evenly; font-size: 20px;"class="card-product">
                  <div class="card-product-infos">
                    <p>No current confirmed applications</p>
                   </div>
            </div>
            <% end %>
        </div>
  </div>
</div>
</div>
<% end %>

app/views/job_applications/new.html.erb
<%= simple_form_for[@job, @application] do %>

<% end %>

app/views/job_applications/show.html.erb
<div class="container">
  <div class="main">

  <% if current_user.employer? %>
    <%= @job.job_title %>
    <%= @job_application.user.username %>
    <%= @job_application.user.skills %>
    <%= @job_application.user.education %>
    <%= @job_application.status %>


  <p><strong>Interview Completion:</strong> <%= @job_application.interview_completion ? "Yes" : "No" %></p>
  <% else %>
  <h1>Job Application Details</h1>

    <p><strong>Job Title:</strong> <%= @job.job_title %></p>
    <p><strong>Company:</strong> <%= @job.company_name %></p>
    <p><strong>Status:</strong> <%= @job_application.status %></p>
    <p><strong>Applicant's Name:</strong> <%= @job_application.user.first_name %></p>
    <p><strong>Applicant's Skills:</strong> <%= @job_application.user.skills %></p>
    <p><strong>Applicant's Education:</strong> <%= @job_application.user.education %></p>


    <% unless @job_application.status == 'confirmed' %>
      <p><strong>Interview Date:</strong> <%= @job_application.interview_date %></p>
      <p><strong>Interview Outcome:</strong> <%= @job_application.interview_outcome %></p>
    <% end %>

  <% end %>

  </div>

  <div class="main">
    <h1>Job Application Chat</h1>

  <%# <%= turbo_stream_from "job_application_#{@job_application.id}_messages" %>
  <div id="messages" class="messages">
    <% @job_application.messages.each do |message| %>
      <%= render "messages/message", message: message, user: current_user %>
    <% end %>
  </div>

  <%= simple_form_for [@job_application, @message],
      html: {class: "d-flex",
          data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f|
  %>
    <% other_user = current_user == @job_application.job.user ? @job_application.user : @job_application.job.user %>
    <%= f.input :content,
      label: false,
      placeholder: "Message #{other_user.username}",
      wrapper_html: {class: "btn-chat-input"}
    %>
    <%= f.submit "Send", class: "btn-chat" %>
  <% end %>

  </div>
</div>

app/views/jobs/index.html.erb
<div class="container" style="margin-bottom:100px;">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <h1 style="color: #1B4965; margin-bottom: 20px;">Search all jobs</h1>
        <%= form_with url: jobs_path, method: :get, class: "simple_form search" do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query,
                params[:query],
                class: "form-control-job",
                id: "search_query",
                placeholder: "Type a keyword"
            %>
          <%= submit_tag "Search Jobs", name: "", class: "btn-job btn-flat" %>
          </div>
        <% end %>
    </div>
    <div class="cards">
      <% if @jobs.any? %>
        <% @jobs.each do |job| %>
          <div class="card-job-index clickable-card" id="border-width" style="justify-content: space-between">
            <div class="d-flex gap-2">
              <%= cl_image_tag job.photo.key if job.photo.attached? %>
              <div class="card-product-infos">
                <h2><%= link_to job.job_title, job_path(job) %> </h2>
                <h4><%= job.company_name %></h4>
                <p><%= job.location %></p>
                <span><%= job.salary %></span>
              </div>
            </div>
            <div class="card-product-infos">
              <% if Favourite.where(job: job, user: current_user).empty? %>
                <%= button_to job_favourites_path(job), class:"fav_button fav-btn" do %>
                <i class="fa-regular fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to favourite_path(Favourite.where(job: job, user: current_user).last), class:"fav-btn", data: {turbo_method: :delete } do %>
                  <i class="fa-solid fa-heart"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <% if current_user.employer %>
          <em>No jobs listed, add one <%= link_to "here", new_job_path %>.</em>
        <% else %>
          <em>Sorry, no jobs found.</em>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>  document.querySelectorAll('.clickable-card').forEach(card => {
  card.addEventListener('click', () => {
    const jobId = card.querySelector('.card-product-infos a').href.split('/').pop();  // Extract job ID from the link within the card
    window.location.href = `/jobs/${jobId}`;  // Redirect to job details page
  });
});
</script>

app/views/jobs/new.html.erb
<div class="container" style="margin-bottom:100px; margin-top: 30px;">
  <div class="page-title">
  <h3>Add New Job</h3>
  </div>
  <div class="add_jobs">
    <%= simple_form_for(@job) do |f| %>
    <div class="form-group">
      <%= f.input :job_title  %>
      <%= f.input :company_name %>
      <%= f.input :company_description %>
      <%= f.input :company_size  %>
      <%= f.input :location  %>
      <%= f.input :salary %>
      <%= f.input :photo, as: :file %>
      <%# <div class=> %>
        <%= f.submit "Add", class: "btn-add-job"  %>
        <% end %>
      <%# </div> %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="show-job" style="margin-bottom:100px">
    <div class="card" style="display:flex; flex-direction:row">
      <div class="card-body" style="width:60%">
      <div class="card-title-show">
        <%= cl_image_tag @job.photo.key if @job.photo.attached? %>
        <div>
          <p class="job-title"><%= @job.job_title %></p>
          <div>
          <i class="fa-solid fa-location-dot"></i> <%= @job.location %>
            <i class="fa-solid fa-clock part-time-btn"></i> Part-time
          </div>
        </div>
      </div>
        <h4>Company  name:</h4>
        <p class="card-text"><%= @job.company_name %></p>
        <h4>Company description: </h4>
        <p class="card-text"><%= @job.company_description %></p>
        <h4>Company size</h4>
        <p class="card-text"><%= @job.company_size %></p>
        <h4>Location: </h4>
        <p class="card-text"><%= @job.location %></p>
        <h4>Job Description: </h4>
        <p class="card-text"><%= @job.job_description %></p>
        <h4>Salary: </h4>
        <p class="card-text"><%= @job.salary %></p>
        <%= link_to "Apply now", job_job_applications_path(@job), data: { turbo_method: :post }, class: "btn btn-primary apply-now-button", style: "width:200px;" %>


        <% if Favourite.where(job: @job, user: current_user).empty? %>
          <%= button_to job_favourites_path(@job), class:"fav_button" do %>
                <i class="fa-regular fa-heart"></i>
          <% end %>
        <% else %>
          <p>This job is already in your Favourites.</p>
          <%= link_to favourite_path(Favourite.where(job: @job, user: current_user).last), data: {turbo_method: :delete } do %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        <% end %>
      </div>
      <div class="card-body" style="width:30%; height:400px">
      <p class="job-title" style="border-bottom: 1px solid #EAEAEA">Job Description</p>
        <p> Published on: 12 Nov, 2019 </p>
        <p> Vacancy: 2 Position </p>
        <p>Salary: 50k - 120k/y </p>
        <p> Location: California, USA </p>
        <p>Job Nature: Full-time
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <div class="container">
  <html>
    <head>
      <title><%= content_for(:title) || "Job Connect Live" %></title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= yield :head %>

      <link rel="manifest" href="/manifest.json">
      <link rel="icon" href="/icon.png" type="image/png">
      <link rel="icon" href="/icon.svg" type="image/svg+xml">
      <link rel="apple-touch-icon" href="/icon.png">
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
    </head>

    <body data-current-user-id="<%= current_user ? current_user.id : "" %>">
        <%= render "shared/navbar" %>
        <%= render "shared/flashes" %>
      <%= yield %>
        <%= render "shared/footer" %>
    </body>
    </div>
</html>

app/views/messages/_message.html.erb
<div
    id="message-<%= message.id %>"
    class="message <%= message.user == user ? 'sent' : 'received' %>"
    data-controller="message"
    data-message-user-id-value="<%= message.user.id %>">
  <small class="message-info">
    <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p class="message-content"><%= message.content %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
       <span style="color:#5FA8D3"><span style="color:#1B4965">Job</span> Connect </span>
    <%end%>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
         <% if user_signed_in? && current_user.employer == true %>
          <li class="nav-item active">
            <%= link_to "All Job Listings", jobs_path, class: "nav-link" %>
          </li>
            <% else %>
          <li class="nav-item active">
            <%= link_to "Jobs", jobs_path, class: "nav-link" %>
          </li>
         <% end %>
          <% if user_signed_in? && current_user.employer == true %>
          <li class="nav-item">
            <%= link_to "Company Applications", job_applications_path, class: "nav-link nav-link-border" %>
          </li>
          <% elsif user_signed_in? && current_user.employer == false %>
          <li class="nav-item">
            <%= link_to "Your Applications", job_applications_path, class: "nav-link nav-link-border" %>
          </li>
            <% end %>
          <% if user_signed_in? && current_user.employer %>
          <li class="nav-item">
              <%= link_to "Recruiting? Post a job", new_job_path, class: "nav-link" %>
          </li>
         <% end %>
      </ul>
      <ul class="navbar-nav me-auto" style="margin-right:0px !important">
          <% if user_signed_in? && current_user.employer == false %>
            <li class="nav-item active">
              <a class="nav-link" href="<%= favourites_path %>">
                <span>Saved Jobs</span>
                <i class="fa-solid fa-heart"></i>
                </a>
            </li>
          <% end %>

        <% if user_signed_in? %>
            <li class="nav-item" style="margin-left: 15px;">
              <p class="nav-link">Hello, <%= current_user.username %>!</p>
            </li>
          <% end %>

           <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= asset_path "profile.gif" %>"/>

             <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "login", new_user_session_path, class: "nav-link" %>
              <a class="dropdown-item" href="#">Another action</a>
              <%= link_to "logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
              </li>
             </ul>

    </div>
    </div>
  </div>
</div>